### ISSUE TITLE
Not working with authentication?

### ISSUE THREAD

**Issue by karl0ss** [thorin8k/runr#1]
Great project and excited to see how this progresses...

Not sure if this has a working branch of RomM where the full integration works?

But I setup the bookmark applet, and all was working fine, until I enabled authentication on my RomM instance, as I have it exposed to the web for friends to use/access, it would seem that the api call being made to get the plat/rom details fails due to not being authenticated and no longer works.

Is there a plan to allow this to work via auth using the bookmarklet? or does the "full integrated version" get around this anyway?

Great work, and keep it up!

**Comment by karl0ss** [comment]
@thorin8k just to upadte you, it would appear it was nothing to do with auth (as the cookie seems to be passsed from the browser) the issue was due to changes in the api on RomM 2.2.0

Here is an updated working bookmarklet for you for 2.2.0+ 

``` js
javascript:(async function(){    const RUNR_PATH = "<RUNR_URL>"; const url = new URL(window.location.href); if(!url.pathname.includes("platform")){ return alert("Website not supported"); } const parts = url.pathname.split("/"); const resp = await fetch(`${url.origin}/api/roms/${parts[3]}`);const data = await resp.json();window.open(`${RUNR_PATH}/?rom=${data?.full_path}&platform=${data?.platform_slug.toLowerCase()}`);})();
```

**Comment by thorin8k** [comment]
Ey @karl0ss, Thanks for the update, and sorry i didn't see the issue before.

Regarding the full integration, the PR was created but I were discussing with the RomM team how this will fit and I've started working inside RomM to include the features of RunR inside.

I think this project will be archived in the following months but i'm still using it 😇


If you want, you can check webRcade too, its something similar to RunR and there is a guide in RomM about setting it up: https://github.com/zurdi15/romm/wiki/WebRcade-Integration

**Comment by karl0ss** [comment]
I was reading your thread on RomM, I like your idea of "links" like sonarr, 

Ill keep an eye out for updates, not tooo sure I will ever use "any" of this, but the ability to do so, is def worth the fun :)
